name: labyrinth
services:
  conduit:
    type: node:custom
    build:
      - npm i -g nodemon
    command: nodemon -w packages -w apps --verbose --ext ts,ttl,js,trig --exec node --inspect=0.0.0.0:47671 -r ts-node/register --inspect packages/knossos/server.ts
    port: 8888
    ssl: true
    overrides:
      image: node:14
      ports:
        - '47671:47671'
      environment:
        TS_NODE_TRANSPILE_ONLY: "true"
        DEBUG: knossos*,hydra*,hydra-box*,labyrinth*
        SPARQL_QUERY_ENDPOINT: http://store:3030/labyrinth
        SPARQL_UPDATE_ENDPOINT: http://store:3030/labyrinth
      depends_on:
        store:
          condition: service_healthy
    moreHttpPorts:
      - 47671
    scanner: false
  store:
    type: compose
    services:
      image: blankdots/jena-fuseki:fuseki3.13.1
      command: /docker-entrypoint.sh /jena-fuseki/start-fuseki.sh
      environment:
        ADMIN_PASSWORD: password
        ENABLE_DATA_WRITE: "true"
        ENABLE_UPDATE: "true"
        ENABLE_UPLOAD: "true"
      volumes:
        - ./fuseki/config.ttl:/data/fuseki/config/config.ttl
      healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:3030 || exit 1
        interval: 5s
        timeout: 3s
        retries: 3

proxy:
  store:
    - db.labyrinth.lndo.site:3030
  conduit:
    - conduit.knossos.lndo.site:8888
