version: "3"

services:
  fuseki:
    image: blankdots/jena-fuseki:fuseki3.13.1
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=password
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_UPLOAD=true
    volumes:
      - ./fuseki/config.ttl:/data/fuseki/config/config.ttl
