### Make all base hydra:Resource and hydra:Class readable

PUT {{base}}/api/authorization/resource-read-all
Content-Type: text/turtle
Authorization: System {{system-token}}

< ../resources/api/authorization/resource-read-all.ttl

### Let authenticated user register accounts

PUT {{base}}/api/authorization/authenticated-users-register
Content-Type: text/turtle
Authorization: System {{system-token}}

< ../resources/api/authorization/authenticated-users-register.ttl
