### Set owner of any created resource

PUT {{base}}/api/events/set-owner
Content-Type: text/turtle
Authorization: System {{system-token}}

< ../resources/api/events/set-owner.ttl

### Set UID of created users

PUT {{base}}/api/events/set-user-uid
Content-Type: text/turtle
Authorization: System {{system-token}}

< ../resources/api/events/set-user-uid.ttl
