### Create User class

PUT {{base}}/api/User
Content-Type: text/turtle
Authorization: System {{system-token}}

< ../resources/api/User.ttl

### Create User Collection class

PUT {{base}}/api/UsersCollection
Content-Type: text/turtle
Authorization: System {{system-token}}

< ../resources/api/UsersCollection.ttl

### Allow system to create hydra:Collection

PUT {{base}}/api/authorization/system-create-collection
Content-Type: text/turtle
Authorization: System {{system-token}}

< ../resources/api/authorization/system-create-collection.ttl

### Create users collection

PUT {{base}}/users
Content-Type: text/turtle
Authorization: System {{system-token}}

< ../resources/users.ttl
